# Generated by Django 4.1.7 on 2023-03-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_incrementablesingletonmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncrementableSingletonModel',
        ),
        migrations.RenameField(
            model_name='dynamicfield',
            old_name='model_schema',
            new_name='table_def',
        ),
        migrations.AlterUniqueTogether(
            name='dynamicfield',
            unique_together={('name', 'table_def')},
        ),
    ]
